server:
    port: 8080

spring:
    application:
        name: medicare-api-gateway

    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        - id: medicare-patient-route
                          uri: lb://medicare-patient-service
                          predicates:
                              - Path=/api/v1/patients/**

                        - id: doctor-service-route
                          uri: lb://medicare-doctor-service
                          predicates:
                              - Path=/api/v1/doctors/**,/api/v1/departments/**

                        - id: medical-service-route
                          uri: lb://medicare-medical-service
                          predicates:
                              - Path=/api/v1/medicals/**

                        - id: pharmacy-service-route
                          uri: lb://medicare-pharmacy-service
                          predicates:
                              - Path=/api/v1/medicines/**,/api/v1/prescriptions/**

                        - id: appointment-service-route
                          uri: lb://medicare-appointment-service
                          predicates:
                              - Path=/api/v1/appointments/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

    instance:
        prefer-ip-address: true
