server:
  port: 8081

spring:
  application:
    name: medicare-patient-service

  datasource:
    url: jdbc:mysql://localhost:3306/medicare_patient_db?createDatabaseIfNotExist=true&useSSL=true&allowPublicKeyRetrieval=true
    username: root
    password: Kien@1109AA.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
