package com.ptit.medicare_medical_service.configuration;

import com.ptit.medicare_medical_service.entity.Medical;
import com.ptit.medicare_medical_service.enums.MedicalStatus;
import com.ptit.medicare_medical_service.repository.MedicalRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Configuration;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Configuration
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final MedicalRepository medicalRepository;

    @Override
    public void run(String... args) throws Exception {
        if (medicalRepository.count() == 0) {
            List<Medical> medicals = List.of(
                    // 1. Tăng huyết áp vô căn (Khoa Tim mạch)
                    Medical.builder()
                            .recordCode("MED202609010001")
                            .appointmentId(101L)
                            .patientId(1L)
                            .doctorId(1L)
                            .visitDate(LocalDateTime.of(2026, 9, 1, 8, 30, 0))
                            .bloodPressure("145/90")
                            .heartRate(82)
                            .temperature(new BigDecimal("36.8"))
                            .weight(new BigDecimal("68.5"))
                            .height(new BigDecimal("170.0"))
                            .spo2(98)
                            .symptoms("Bệnh nhân đau đầu vùng chẩm, chóng mặt nhẹ khi thay đổi tư thế, hồi hộp trống ngực.")
                            .icd10Code("I10")
                            .diagnosis("Tăng huyết áp nguyên phát giai đoạn 2")
                            .results("Điện tâm đồ (ECG): Dày thất trái nhẹ. Siêu âm tim: EF 62%, van tim xơ hóa nhẹ. Xét nghiệm máu: Cholesterol toàn phần 5.8 mmol/L.")
                            .treatmentPlan("Amlodipine 5mg x 1 viên/ngày uống buổi sáng. Ăn giảm muối (< 5g/ngày), hạn chế mỡ động vật, đi bộ 30 phút/ngày.")
                            .followUpDate(LocalDate.of(2026, 10, 1))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 2. Viêm dạ dày mạn tính (Khoa Nội tiêu hóa)
                    Medical.builder()
                            .recordCode("MED202609010002")
                            .appointmentId(102L)
                            .patientId(2L)
                            .doctorId(2L)
                            .visitDate(LocalDateTime.of(2026, 9, 1, 9, 15, 0))
                            .bloodPressure("115/75")
                            .heartRate(76)
                            .temperature(new BigDecimal("36.5"))
                            .weight(new BigDecimal("52.0"))
                            .height(new BigDecimal("158.0"))
                            .spo2(99)
                            .symptoms("Đau âm ỉ vùng thượng vị, ợ chua, đầy bụng khó tiêu tăng sau khi ăn no.")
                            .icd10Code("K29.7")
                            .diagnosis("Viêm dạ dày - tá tràng mạn tính nghi nhiễm H.pylori")
                            .results("Nội soi thực quản dạ dày: Niêm mạc hang vị phù nề, sung huyết rải rác, Clo-test (+).")
                            .treatmentPlan("Phác đồ 4 thuốc có Bismuth x 14 ngày: Esomeprazole 40mg (2 lần/ngày), Bismuth subcitrate 120mg, Tetracycline 500mg, Metronidazole 500mg. Kiêng chua cay, rượu bia, cà phê.")
                            .followUpDate(LocalDate.of(2026, 9, 28))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 3. Viêm họng cấp tính ở trẻ nhỏ (Khoa Nhi)
                    Medical.builder()
                            .recordCode("MED202609020001")
                            .appointmentId(103L)
                            .patientId(3L)
                            .doctorId(3L)
                            .visitDate(LocalDateTime.of(2026, 9, 2, 10, 0, 0))
                            .bloodPressure("100/65")
                            .heartRate(95)
                            .temperature(new BigDecimal("38.5"))
                            .weight(new BigDecimal("18.0"))
                            .height(new BigDecimal("105.0"))
                            .spo2(97)
                            .symptoms("Trẻ sốt cao liên tục 2 ngày, nuốt đau, quấy khóc, ho húng hắng, ăn kém nôn trớ.")
                            .icd10Code("J02.9")
                            .diagnosis("Viêm họng cấp có mủ do liên cầu")
                            .results("Họng đỏ rực, hai amidan sưng to độ II có chấm mủ trắng, hạch góc hàm hai bên sưng đau nhẹ. Test nhanh liên cầu A (+).")
                            .treatmentPlan("Augmentin 250mg x 2 gói/ngày chia 2 lần sau ăn x 7 ngày. Hạ sốt Paracetamol 250mg khi nhiệt độ > 38.5°C. Xịt họng sát khuẩn thảo dược.")
                            .followUpDate(LocalDate.of(2026, 9, 9))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 4. Viêm xoang mạn tính (Khoa Tai Mũi Họng)
                    Medical.builder()
                            .recordCode("MED202609020002")
                            .appointmentId(104L)
                            .patientId(4L)
                            .doctorId(4L)
                            .visitDate(LocalDateTime.of(2026, 9, 2, 14, 20, 0))
                            .bloodPressure("120/80")
                            .heartRate(72)
                            .temperature(new BigDecimal("36.7"))
                            .weight(new BigDecimal("60.0"))
                            .height(new BigDecimal("165.0"))
                            .spo2(98)
                            .symptoms("Nghẹt mũi luân phiên hai bên, chảy dịch mũi vàng đục xuống họng, nhức gốc mũi và trán.")
                            .icd10Code("J32.9")
                            .diagnosis("Viêm xoang hàm - sàng mạn tính đợt cấp")
                            .results("Nội soi tai mũi họng: Khe giữa hai bên có mủ đặc màu vàng, cuốn mũi dưới nề to thoái hóa dạng polyp.")
                            .treatmentPlan("Cefuroxime 500mg x 2 viên/ngày x 7 ngày. Xịt mũi Momex 50mcg ngày 2 nhát mỗi bên. Rửa mũi bằng nước muối sinh lý ấm ngày 3 lần.")
                            .followUpDate(LocalDate.of(2026, 9, 16))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 5. Cận thị hai mắt (Khoa Mắt)
                    Medical.builder()
                            .recordCode("MED202609030001")
                            .appointmentId(105L)
                            .patientId(5L)
                            .doctorId(5L)
                            .visitDate(LocalDateTime.of(2026, 9, 3, 8, 45, 0))
                            .bloodPressure("110/70")
                            .heartRate(75)
                            .temperature(new BigDecimal("36.6"))
                            .weight(new BigDecimal("55.0"))
                            .height(new BigDecimal("162.0"))
                            .spo2(99)
                            .symptoms("Nhìn xa mờ, hay nheo mắt khi nhìn màn hình máy tính, mỏi mắt vào cuối ngày.")
                            .icd10Code("H52.1")
                            .diagnosis("Cận thị đơn thuần hai mắt kèm mỏi điều tiết")
                            .results("Thị lực không kính: MP 2/10, MT 2/10. Khúc xạ sau liệt điều tiết: MP -2.25 Diop, MT -2.50 Diop. Nhãn áp: MP 15 mmHg, MT 16 mmHg (bình thường). Đáy mắt chưa thấy tổn thương võng mạc.")
                            .treatmentPlan("Cắt kính theo đơn khúc xạ đạt thị lực 10/10 hai mắt. Nhỏ mắt nước mắt nhân tạo Systane Ultra ngày 4 lần. Áp dụng quy tắc 20-20-20 khi làm việc máy tính.")
                            .followUpDate(LocalDate.of(2027, 3, 3))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 6. Thoái hóa khớp gối (Khoa Chấn thương chỉnh hình)
                    Medical.builder()
                            .recordCode("MED202609030002")
                            .appointmentId(106L)
                            .patientId(6L)
                            .doctorId(6L)
                            .visitDate(LocalDateTime.of(2026, 9, 3, 11, 10, 0))
                            .bloodPressure("130/85")
                            .heartRate(78)
                            .temperature(new BigDecimal("36.5"))
                            .weight(new BigDecimal("72.0"))
                            .height(new BigDecimal("168.0"))
                            .spo2(98)
                            .symptoms("Đau khớp gối phải khi đứng lên ngồi xuống và leo cầu thang, có tiếng lạo xạo trong khớp.")
                            .icd10Code("M17.9")
                            .diagnosis("Thoái hóa khớp gối nguyên phát độ II (Kellgren & Lawrence)")
                            .results("X-quang khớp gối hai tư thế: Hẹp nhẹ khe khớp bên trong, gai xương rìa mâm chày, không tràn dịch khớp.")
                            .treatmentPlan("Celecoxib 200mg x 1 viên/ngày sau ăn sáng x 10 ngày. Glucosamine sulfate 1500mg/ngày kéo dài 3 tháng. Giảm cân, hạn chế ngồi xổm, bơi lội hoặc đạp xe nhẹ nhàng.")
                            .followUpDate(LocalDate.of(2026, 10, 3))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 7. Mụn trứng cá viêm nặng (Khoa Da liễu)
                    Medical.builder()
                            .recordCode("MED202609040001")
                            .appointmentId(107L)
                            .patientId(7L)
                            .doctorId(7L)
                            .visitDate(LocalDateTime.of(2026, 9, 4, 9, 0, 0))
                            .bloodPressure("115/70")
                            .heartRate(80)
                            .temperature(new BigDecimal("36.6"))
                            .weight(new BigDecimal("48.0"))
                            .height(new BigDecimal("156.0"))
                            .spo2(99)
                            .symptoms("Nổi nhiều nốt sẩn đỏ, mụn mủ vùng hai má và trán, đau ngứa nhẹ, da nhiều dầu nhờn.")
                            .icd10Code("L70.0")
                            .diagnosis("Trứng cá viêm mức độ trung bình - nặng (Acne vulgaris)")
                            .results("Khám lâm sàng: Nhiều sẩn viêm, mụn mủ đường kính 2-4mm, có vài nang mụn sâu, sẹo thâm rải rác.")
                            .treatmentPlan("Doxycycline 100mg x 1 viên/ngày sau ăn trưa x 30 ngày. Bôi gel Adapalene 0.1% + Benzoyl Peroxide 2.5% buổi tối. Sữa rửa mặt dịu nhẹ kiểm soát bã nhờn.")
                            .followUpDate(LocalDate.of(2026, 10, 4))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 8. Đái tháo đường thai kỳ (Khoa Sản phụ khoa)
                    Medical.builder()
                            .recordCode("MED202609040002")
                            .appointmentId(108L)
                            .patientId(8L)
                            .doctorId(8L)
                            .visitDate(LocalDateTime.of(2026, 9, 4, 15, 30, 0))
                            .bloodPressure("120/75")
                            .heartRate(85)
                            .temperature(new BigDecimal("36.8"))
                            .weight(new BigDecimal("63.0"))
                            .height(new BigDecimal("160.0"))
                            .spo2(99)
                            .symptoms("Thai 26 tuần, tăng cân nhanh 3kg trong tháng qua, uống nước nhiều, tiểu đêm 2-3 lần.")
                            .icd10Code("O24.4")
                            .diagnosis("Đái tháo đường thai kỳ (Gestational diabetes mellitus)")
                            .results("Nghiệm pháp dung nạp glucose đường uống (OGTT 75g): Lúc đói 5.3 mmol/L, sau 1h 10.5 mmol/L, sau 2h 8.9 mmol/L (Dương tính). Siêu âm thai: Thai tương đương 26 tuần 3 ngày, ước lượng cân nặng 980g.")
                            .treatmentPlan("Tư vấn chế độ dinh dưỡng tiết chế carbohydrate, chia nhỏ 5-6 bữa/ngày. Tự theo dõi đường huyết mao mạch 4 lần/ngày (lúc đói và sau ăn 2h). Tái khám đánh giá lại sau 2 tuần.")
                            .followUpDate(LocalDate.of(2026, 9, 18))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 9. Đau nửa đầu Migraine (Khoa Ngoại thần kinh)
                    Medical.builder()
                            .recordCode("MED202609050001")
                            .appointmentId(109L)
                            .patientId(9L)
                            .doctorId(9L)
                            .visitDate(LocalDateTime.of(2026, 9, 5, 8, 30, 0))
                            .bloodPressure("125/80")
                            .heartRate(70)
                            .temperature(new BigDecimal("36.5"))
                            .weight(new BigDecimal("65.0"))
                            .height(new BigDecimal("172.0"))
                            .spo2(98)
                            .symptoms("Đau giật theo nhịp mạch nửa đầu bên phải, sợ ánh sáng và tiếng động, buồn nôn khi lên cơn đau.")
                            .icd10Code("G43.9")
                            .diagnosis("Đau nửa đầu Migraine không có tiền triệu")
                            .results("Chụp cộng hưởng từ sọ não (MRI 3.0T): Chưa phát hiện tổn thương nhu mô não hay dị dạng mạch máu. Khám thần kinh không có dấu hiệu khu trú.")
                            .treatmentPlan("Cắt cơn: Zolmitriptan 2.5mg uống khi bắt đầu đau. Dự phòng: Flunarizine 5mg uống tối trước ngủ x 2 tháng. Ghi nhật ký cơn đau và tránh các yếu tố kích phát (stress, thức khuya).")
                            .followUpDate(LocalDate.of(2026, 11, 5))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 10. Đái tháo đường typ 2 (Khoa Nội tiết)
                    Medical.builder()
                            .recordCode("MED202609050002")
                            .appointmentId(110L)
                            .patientId(10L)
                            .doctorId(10L)
                            .visitDate(LocalDateTime.of(2026, 9, 5, 10, 45, 0))
                            .bloodPressure("135/85")
                            .heartRate(84)
                            .temperature(new BigDecimal("36.6"))
                            .weight(new BigDecimal("75.0"))
                            .height(new BigDecimal("165.0"))
                            .spo2(98)
                            .symptoms("Bệnh nhân cảm thấy mệt mỏi thường xuyên, ăn nhiều uống nhiều nhưng sụt 4kg trong 2 tháng.")
                            .icd10Code("E11.9")
                            .diagnosis("Đái tháo đường typ 2 chưa có biến chứng cấp")
                            .results("Glucose máu lúc đói: 8.9 mmol/L. HbA1c: 8.2%. Men gan ALT/AST: 35/32 U/L. Chức năng thận Creatinine: 78 umol/L, eGFR: 92 ml/min.")
                            .treatmentPlan("Metformin 850mg x 2 viên/ngày uống sau ăn sáng - chiều. Gliclazide MR 60mg x 1 viên uống sáng. Ăn giảm tinh bột nhanh, tăng cường rau xanh, tái khám xét nghiệm lại đường huyết.")
                            .followUpDate(LocalDate.of(2026, 10, 5))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 11. Dị ứng thức ăn cấp tính (Khoa Hồi sức cấp cứu)
                    Medical.builder()
                            .recordCode("MED202609060001")
                            .appointmentId(111L)
                            .patientId(11L)
                            .doctorId(11L)
                            .visitDate(LocalDateTime.of(2026, 9, 6, 11, 20, 0))
                            .bloodPressure("105/65")
                            .heartRate(98)
                            .temperature(new BigDecimal("37.1"))
                            .weight(new BigDecimal("58.0"))
                            .height(new BigDecimal("163.0"))
                            .spo2(96)
                            .symptoms("Bệnh nhân nổi ban mày đay toàn thân, ngứa dữ dội, khó thở nhẹ sau khi ăn hải sản tôm cua 30 phút.")
                            .icd10Code("T78.4")
                            .diagnosis("Phản ứng phản vệ độ II do dị ứng hải sản")
                            .results("Mạch nhanh 98 ck/phút, thở rít nhẹ thì thở vào, SpO2 96% khí trời, ban mày đay sẩn phù khắp người. Chưa tụt huyết áp.")
                            .treatmentPlan("Tiêm bắp Adrenalin 0.3mg ngay lập tức. Methylprednisolone 40mg tiêm tĩnh mạch x 1 lọ. Fexofenadine 180mg x 1 viên/ngày. Lưu theo dõi tại viện 6 giờ.")
                            .followUpDate(LocalDate.of(2026, 9, 8))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 12. Viêm nha chu mạn tính (Khoa Răng Hàm Mặt)
                    Medical.builder()
                            .recordCode("MED202609060002")
                            .appointmentId(112L)
                            .patientId(12L)
                            .doctorId(12L)
                            .visitDate(LocalDateTime.of(2026, 9, 6, 14, 0, 0))
                            .bloodPressure("118/78")
                            .heartRate(74)
                            .temperature(new BigDecimal("36.7"))
                            .weight(new BigDecimal("62.0"))
                            .height(new BigDecimal("167.0"))
                            .spo2(99)
                            .symptoms("Chảy máu chân răng tự nhiên và khi đánh răng, hơi thở có mùi hôi, răng hàm dưới lung lay nhẹ.")
                            .icd10Code("K05.3")
                            .diagnosis("Viêm nha chu mạn tính lan tỏa giai đoạn II")
                            .results("Khám răng: Cao răng dưới lợi độ III, túi nha chu sâu 4-5mm rải rác vùng răng hàm, lợi sưng đỏ phì đại.")
                            .treatmentPlan("Lấy cao răng trên và dưới lợi toàn hàm, nạo túi nha chu làm sạch chân răng. Súc miệng Chlorhexidine 0.12% ngày 2 lần. Spiramycin 1.5 MUI x 2 viên/ngày x 5 ngày.")
                            .followUpDate(LocalDate.of(2026, 9, 20))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 13. Polyp đại tràng lành tính (Khoa Ung bướu)
                    Medical.builder()
                            .recordCode("MED202609070001")
                            .appointmentId(113L)
                            .patientId(13L)
                            .doctorId(13L)
                            .visitDate(LocalDateTime.of(2026, 9, 7, 8, 30, 0))
                            .bloodPressure("122/80")
                            .heartRate(76)
                            .temperature(new BigDecimal("36.5"))
                            .weight(new BigDecimal("66.0"))
                            .height(new BigDecimal("170.0"))
                            .spo2(99)
                            .symptoms("Rối loạn tiêu hóa thỉnh thoảng đi ngoài phân lỏng xen kẽ táo bón, có vệt máu tươi bám theo phân.")
                            .icd10Code("D12.6")
                            .diagnosis("Polyp đại tràng sigma cuống ngắn đã can thiệp cắt nội soi")
                            .results("Nội soi đại tràng toàn bộ: Phát hiện 01 polyp kích thước 12mm cuống ngắn tại đại tràng sigma. Đã can thiệp cắt polyp bằng thòng lọng điện (snare polypectomy) thành công, chân cắt cầm máu tốt.")
                            .treatmentPlan("Gửi bệnh phẩm làm giải phẫu bệnh lý vi thể. Nghỉ ngơi tại chỗ, ăn cháo loãng nguội trong 24h đầu. Tránh vận động mạnh hoặc nâng vác nặng trong 7 ngày.")
                            .followUpDate(LocalDate.of(2026, 9, 14))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 14. Cơn đau thắt ngực không đặc hiệu (Khoa Tim mạch)
                    Medical.builder()
                            .recordCode("MED202609070002")
                            .appointmentId(114L)
                            .patientId(14L)
                            .doctorId(15L)
                            .visitDate(LocalDateTime.of(2026, 9, 7, 10, 15, 0))
                            .bloodPressure("138/88")
                            .heartRate(88)
                            .temperature(new BigDecimal("36.6"))
                            .weight(new BigDecimal("70.0"))
                            .height(new BigDecimal("169.0"))
                            .spo2(97)
                            .symptoms("Đau tức ngực trái lan lên vai trái kéo dài khoảng 5-10 phút khi gắng sức đi nhanh hoặc leo dốc.")
                            .icd10Code("I20.9")
                            .diagnosis("Thiếu máu cơ tim cục bộ mạn tính / Cơn đau thắt ngực ổn định")
                            .results("ECG: Sóng T âm nhẹ ở các chuyển đạo V4-V6. Men tim Troponin I âm tính (< 0.01 ng/mL). Siêu âm tim: Giảm động nhẹ vùng mỏm thất trái.")
                            .treatmentPlan("Chỉ định chụp cắt lớp vi tính mạch vành 128 dãy có cản quang (MSCT). Thuốc điều trị: Aspirin 81mg x 1 viên/ngày, Atorvastatin 20mg tối, Bisoprolol 2.5mg sáng.")
                            .followUpDate(LocalDate.of(2026, 9, 14))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 15. Viêm tai giữa cấp (Khoa Tai Mũi Họng)
                    Medical.builder()
                            .recordCode("MED202609080001")
                            .appointmentId(115L)
                            .patientId(15L)
                            .doctorId(17L)
                            .visitDate(LocalDateTime.of(2026, 9, 8, 14, 45, 0))
                            .bloodPressure("110/70")
                            .heartRate(82)
                            .temperature(new BigDecimal("37.8"))
                            .weight(new BigDecimal("45.0"))
                            .height(new BigDecimal("152.0"))
                            .spo2(98)
                            .symptoms("Đau nhức tai phải dữ dội lan ra sau gáy, ù tai, nghe kém, có sốt nhẹ kèm chảy mũi trong.")
                            .icd10Code("H66.9")
                            .diagnosis("Viêm tai giữa cấp mủ giai đoạn ứ mủ tai phải")
                            .results("Nội soi tai: Màng nhĩ phải đỏ rực, phồng hình mặt kính đồng hồ, mất nón sáng, chưa thủng màng nhĩ.")
                            .treatmentPlan("Cefixime 200mg x 2 viên/ngày x 7 ngày. Giảm đau hạ sốt Paracetamol 500mg. Nhỏ mũi Otrivin 0.05% để thông vòi tai. Tuyệt đối không tự ý nhỏ thuốc vào tai khi chưa thủng màng nhĩ.")
                            .followUpDate(LocalDate.of(2026, 9, 15))
                            .status(MedicalStatus.FINALIZED)
                            .isDeleted(false)
                            .build(),

                    // 3 hồ sơ đã bị xóa mềm (isDeleted = true) để kiểm thử danh sách xóa mềm và chức năng khôi phục
                    Medical.builder()
                            .recordCode("MED202608250001")
                            .appointmentId(901L)
                            .patientId(1L)
                            .doctorId(1L)
                            .visitDate(LocalDateTime.of(2026, 8, 25, 9, 0, 0))
                            .bloodPressure("130/80")
                            .heartRate(75)
                            .temperature(new BigDecimal("36.5"))
                            .weight(new BigDecimal("68.0"))
                            .height(new BigDecimal("170.0"))
                            .spo2(98)
                            .symptoms("Khám sức khỏe tổng quát định kỳ.")
                            .icd10Code("Z00.0")
                            .diagnosis("Kiểm tra sức khỏe tổng quát bình thường")
                            .results("Các chỉ số xét nghiệm và cận lâm sàng nằm trong giới hạn cho phép.")
                            .treatmentPlan("Duy trì lối sống lành mạnh, tập thể dục thường xuyên.")
                            .followUpDate(LocalDate.of(2027, 8, 25))
                            .status(MedicalStatus.CANCELLED)
                            .isDeleted(true)
                            .build(),

                    Medical.builder()
                            .recordCode("MED202608260002")
                            .appointmentId(902L)
                            .patientId(2L)
                            .doctorId(2L)
                            .visitDate(LocalDateTime.of(2026, 8, 26, 14, 15, 0))
                            .bloodPressure("120/80")
                            .heartRate(80)
                            .temperature(new BigDecimal("36.6"))
                            .weight(new BigDecimal("52.0"))
                            .height(new BigDecimal("158.0"))
                            .spo2(99)
                            .symptoms("Hồ sơ lập nhầm mã bệnh nhân khi tiếp đón.")
                            .icd10Code("R10.4")
                            .diagnosis("Đau bụng không đặc hiệu")
                            .results("Chưa thực hiện cận lâm sàng.")
                            .treatmentPlan("Hủy hồ sơ do nhập sai thông tin ban đầu.")
                            .followUpDate(null)
                            .status(MedicalStatus.CANCELLED)
                            .isDeleted(true)
                            .build(),

                    Medical.builder()
                            .recordCode("MED202608270003")
                            .appointmentId(903L)
                            .patientId(3L)
                            .doctorId(3L)
                            .visitDate(LocalDateTime.of(2026, 8, 27, 16, 0, 0))
                            .bloodPressure("100/60")
                            .heartRate(90)
                            .temperature(new BigDecimal("37.0"))
                            .weight(new BigDecimal("18.0"))
                            .height(new BigDecimal("105.0"))
                            .spo2(98)
                            .symptoms("Khám lại theo lịch hẹn nhưng người nhà xin dời lịch.")
                            .icd10Code("Z09.8")
                            .diagnosis("Tái khám theo dõi điều trị")
                            .results("Bệnh nhi đã hết sốt, ăn uống tốt.")
                            .treatmentPlan("Hẹn lại vào ngày khác theo yêu cầu gia đình.")
                            .followUpDate(null)
                            .status(MedicalStatus.CANCELLED)
                            .isDeleted(true)
                            .build()
            );

            medicalRepository.saveAll(medicals);
        }
    }
}
